name: build-and-deploy-image
run-name: Build and deploy image started by ${{ github.actor }}

on:
  push:
    branches:
    - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          uses: actions/checkout@v5
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_CONTAINER_REGISTRY_SERVER}}
            username: ${{ secrets.ACR_CONTAINER_REGISTRY_USER }}
            password: ${{ secrets.ACR_CONTAINER_REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.ACR_CONTAINER_REGISTRY_SERVER }}/sampleapp:${{ github.sha }}
            docker push ${{ secrets.ACR_CONTAINER_REGISTRY_SERVER }}/sampleapp:${{ github.sha }}